# Generated by Django 4.1.4 on 2022-12-11 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_in_cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_product', models.IntegerField(null=True)),
                ('product_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
