# Generated by Django 4.1.2 on 2022-11-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_in_cart',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product_in_cart',
            name='quantity_product',
        ),
        migrations.AddField(
            model_name='product_in_cart',
            name='products',
            field=models.JSONField(null=True),
        ),
    ]
