# Generated by Django 4.1.4 on 2022-12-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('price', models.FloatField(max_length=9, null=True, verbose_name='Цена')),
                ('layer_field', models.CharField(choices=[('однослойный', 'однослойный'), ('многослойный', 'многослойный')], max_length=15, null=True, verbose_name='Количество слоев')),
                ('category', models.CharField(max_length=25, null=True, verbose_name='Категория')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('photo', models.ImageField(null=True, upload_to='uploads/', verbose_name='Фотография')),
                ('quantity_in_cart', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
