# Generated by Django 4.1.2 on 2022-11-13 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
