# Generated by Django 4.1.2 on 2022-11-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_date_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='order_date',
        ),
    ]
