# Generated by Django 4.1.2 on 2022-11-20 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_date_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
