# Generated by Django 4.1.2 on 2022-11-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Готовится', 'Готовится'), ('Доставляется', 'Доставляется'), ('Выполнен', 'Выполнен')], default='Готовится', max_length=15, null=True),
        ),
    ]
