# Generated by Django 4.1.3 on 2022-11-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Готовится', 'Готовится'), ('Доставляется', 'Доставляется'), ('Выполнен', 'Выполнен')], default='Готовится', max_length=15, null=True, verbose_name='Вермя доставки'),
        ),
    ]
